[settings]
lockfile = true

[tools]
actionlint = "latest"
devcontainer-cli = "latest"
go = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:gotest.tools/gotestsum" = "latest"
golangci-lint = "latest"
goreleaser = "latest"
node = "latest"
"npm:markdown-link-check" = "latest"
"npm:vite" = "latest"
"npm:vitest" = "latest"
pnpm = "latest"
prettier = "latest"
rumdl = "latest"
shellcheck = "latest"
typos = "latest"

[env]
MISE_CONFIG_ROOT="."
SHELL="/bin/bash" # hardcoded here so the doc generation script uses it as default.

[tasks.'deps:wasm']
description = "download the dependencies for the wasm wrapper"
dir = "wasm"
run = '''
pnpm install
'''

[tasks.'build:cli']
description = "build the cli"
run = '''
go build ./cmd/scw
'''

[tasks.'build:wasm']
description = "build the wasm wrapper"
depends = ["deps:wasm"]
run = '''
GOOS=js GOARCH=wasm go build ./cmd/scw-wasm
mv scw-wasm wasm/cli.wasm
'''

[tasks.'build:wasm-tester']
description = "build the wasm wrapper tester"
depends = ["deps:wasm"]
run = '''
GOOS=js GOARCH=wasm go build ./cmd/scw-wasm-tester
mv scw-wasm-tester wasm/cliTester.wasm
'''

[tasks.'build:doc']
description = "build the documentation"
run = '''
rm -rf ./docs/commands
mkdir ./docs/commands
go run ./cmd/scw-doc-gen
rumdl fmt -s ./docs
'''

[tasks.'lint:cli']
description = "lint the cli"
usage = '''
arg "[packages]" {
  help "target packages to test"
  default "./..."
}
'''
run = '''
golangci-lint run {{usage.packages}}
'''

[tasks.'lint:docker']
description = "lint the docker image"
run = '''
docker build --check .
'''

[tasks.'lint:wasm']
description = "lint the wasm wrapper"
dir = "wasm"
run = '''
prettier --check .
'''

[tasks.'lint:doc']
description = "lint the documentation"
depends = ["build:doc"]
run = '''
rumdl check ./docs
typos ./docs
'''

[tasks.'lint:actions']
description = "lint the workflows"
run = '''
actionlint
'''

[tasks.'test:cli']
description = "test the cli"
depends = ["build:cli"]
usage = '''
arg "[packages]" {
  help "target packages to test"
  default "./..."
}
'''
run = '''
gotestsum ${usage_packages}
'''

[tasks.'test:wasm']
description = "test the wasm wrapper"
depends = ["build:wasm", "build:wasm-tester"]
dir = "wasm"
run = '''
vitest ./src
'''

# [tasks.'test:doc']
# description = "test the documentation"
# run = '''
# markdown-link-check -c ./.markdownlinkcheck.json -q ./docs
# '''

[tasks.ci]
description = ""
depends = ["test:*", "build:*", "lint:*"]

[tasks.release]
description = "release a new cli version"
run = '''
false
'''
