package docgen

const tplStr = `

{{- define "index" -}}
  {{ template "do_not_edit" }}
  ### List of namespace:
  {{ range $name, $namespace := .Namespaces -}}
    - [{{ $name }}]("./{{ $name }}.md") 
  {{ end }}
{{- end -}}



{{- define "namespace" -}}
  {{ template "do_not_edit" }}
  # Documentation for scw {{ .Cmd.Namespace }}
  
  {{ range $resourceName, $resource := .Resources -}}
    {{ if $resource.Verbs | len -}}
      - {{ $resourceName }}
      {{ range $verbName, $cmd := $resource.Verbs }}
        - [{{ $verbName }}]("#{{ $resourceName}}-{{ $verbName }}")
      {{- end -}}
    {{- else -}}
      - [{{ $resourceName }}]("#{{ $resourceName }}")
    {{ end }}
  {{ end }}
  
  {{ range $resourceName, $resource := .Resources -}}
    ## scw {{ $.Cmd.Namespace }} {{ $resourceName }}
    {{ if $resource.Verbs | len -}}
      {{ range $verbName, $cmd := $resource.Verbs }}
        ### scw {{ $.Cmd.Namespace }} {{ $resourceName }} {{ $verbName }}
        {{ template "cmd" $cmd }}
      {{- end -}}
    {{- else -}}
      {{ template "cmd" $resource.Cmd }}
    {{ end }}
  {{ end }}
{{- end -}}

{{- define "cmd" -}}
  ** Usage **:  {{ .Namespace }} {{ .Resource }} {{ .Verb }}
  ** Short **:  {{ .Short }}
  ** Long **:  {{ .Long }}
  {{ if .Examples }}
    ** Examples **:
    {{ range $example := .Examples }}
      - {{ $example.Short }}
    {{ end }}
  {{ end }}
{{- end -}}

{{- define "do_not_edit" -}}
  <!-- DO NOT EDIT: this file is automatically generated using scw-doc-gen -->
{{- end -}}

`
