package mongodb_test

import (
	"fmt"
	"testing"

	"github.com/scaleway/scaleway-cli/v2/core"
	"github.com/scaleway/scaleway-cli/v2/internal/namespaces/mongodb/v1"
	mongodbSDK "github.com/scaleway/scaleway-sdk-go/api/mongodb/v1"
	"github.com/stretchr/testify/assert"
)

func Test_CreateInstancePasswordGenerator(t *testing.T) {
	t.Run("Generated when unspecified", core.Test(&core.TestConfig{
		Commands: mongodb.GetCommands(),
		// No password given: it must be generated by default.
		Cmd: fmt.Sprintf(
			"scw mongodb instance create --wait name=%s node-type=mgdb-play2-nano user-name=admin endpoints.0.public-network={} ",
			"generated-password",
		),
		// do not check the golden as the password generated locally and on CI will necessarily be different
		Check: core.TestCheckCombine(
			core.TestCheckExitCode(0),
			func(t *testing.T, ctx *core.CheckFuncCtx) {
				t.Helper()
				if ctx.Result != nil {
					assert.NotEmpty(t, ctx.Result.(*mongodbSDK.Instance).ID)
				}
			},
		),
		AfterFunc: core.ExecAfterCmd("scw mongodb instance delete {{ .CmdResult.ID }}"),
	}))
}
