name: Slack Announcement

permissions:
  contents: read

on:
  release:
    types:
      - published

jobs:
  slack:
    runs-on: "${{ vars.RUNS_ON || 'ubuntu-latest' }}"
    steps:
      - name: Announce on slack
        env:
          TAG_NAME: "${{ github.event.release.tag_name }}"
          HTML_URL: "${{ github.event.release.html_url }}"
          WEBHOOKS: "${{ secrets.SLACK_WEBHOOKS }}"
        run: |
          for webhook in $WEBHOOKS; do
            jq -n --arg tag_name "$TAG_NAME" --arg html_url "$HTML_URL" '{
            	"blocks": [
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "New CLI release $tag_name ! :tada: :rocket:\nCheck changelog on <$html_url|release page>"
                    }
                }
              ]
            }' | curl -X POST -H 'Content-type: application/json' -d @- "$webhook" 
          done
