name: ci

on:
  merge_group:
  pull_request:
  push:
    tags: ["*"]
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true

jobs:
  ci:
    runs-on: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
    timeout-minutes: 10
    steps:
      - name: Set git to use LF to avoid problem with goldens on windows
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: jdx/mise-action@v3
        with:
          version: 2026.9.3
      - run: mise run ci

