name: release
permissions:
  contents: write
  id-token: write # Required for OIDC (MCP and scaleway-cli-wasm)

on:
  push:
    tags: ["v*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true

jobs:
  release:
    runs-on: ${{ vars.RUNS_ON || 'ubuntu-latest' }}
    timeout-minutes: 10
    steps:
      - name: Set git to use LF to avoid problem with goldens on windows
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: jdx/mise-action@v3
        with:
          version: 2026.9.3
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Release the version
        run: mise run release --snapshot false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WINGET_TOKEN: ${{ secrets.WINGET_TOKEN }}

